export interface Address {
  street: string;
  city: string;
  state: string;
  zip: string;
}

export type ClientType = "Residential" | "Commercial";
export type ClientStatus = "Lead" | "Active" | "In Storage" | "Past" | "Inactive";

export interface Client {
  id: string;
  name: string;
  type: ClientType;
  status: ClientStatus;
  primaryContactName: string;
  email: string;
  phone: string;
  billingAddress: Address;
  originAddress?: Address;
  destinationAddress?: Address;
  accountOwner: string;
  createdDate: string;
  lastActivityDate: string;
  notes?: string;
}

export const clients: Client[] = [
  {
    id: "CLT-1001",
    name: "Danielle Ruiz",
    type: "Residential",
    status: "Active",
    primaryContactName: "Danielle Ruiz",
    email: "danielle.ruiz@example.com",
    phone: "(408) 555-0142",
    billingAddress: { street: "214 Willow Ave", city: "San Jose", state: "CA", zip: "95125" },
    originAddress: { street: "214 Willow Ave", city: "San Jose", state: "CA", zip: "95125" },
    destinationAddress: { street: "88 Harbor View Dr", city: "Redwood City", state: "CA", zip: "94065" },
    accountOwner: "Sam Okafor",
    createdDate: "2026-05-02",
    lastActivityDate: "2026-08-14",
    notes: "Requested extra padding for a piano.",
  },
  {
    id: "CLT-1002",
    name: "Bellweather Logistics",
    type: "Commercial",
    status: "In Storage",
    primaryContactName: "Marcus Yee",
    email: "marcus.yee@example.com",
    phone: "(510) 555-0178",
    billingAddress: { street: "4400 Distribution Way", city: "Oakland", state: "CA", zip: "94621" },
    accountOwner: "Omar Haddad",
    createdDate: "2025-11-19",
    lastActivityDate: "2026-08-20",
    notes: "Overflow inventory, quarterly billing.",
  },
  {
    id: "CLT-1003",
    name: "Priya Nair",
    type: "Residential",
    status: "Lead",
    primaryContactName: "Priya Nair",
    email: "priya.nair@example.com",
    phone: "(650) 555-0193",
    billingAddress: { street: "77 Alma St", city: "Palo Alto", state: "CA", zip: "94301" },
    accountOwner: "Fatima Rahman",
    createdDate: "2026-08-10",
    lastActivityDate: "2026-08-22",
  },
  {
    id: "CLT-1004",
    name: "Whitfield & Sons Law",
    type: "Commercial",
    status: "Past",
    primaryContactName: "Georgia Whitfield",
    email: "georgia.whitfield@example.com",
    phone: "(408) 555-0111",
    billingAddress: { street: "900 Market St, Suite 4", city: "San Jose", state: "CA", zip: "95113" },
    originAddress: { street: "900 Market St, Suite 4", city: "San Jose", state: "CA", zip: "95113" },
    destinationAddress: { street: "1200 Corporate Center Dr", city: "Sunnyvale", state: "CA", zip: "94089" },
    accountOwner: "Sam Okafor",
    createdDate: "2025-03-14",
    lastActivityDate: "2025-06-02",
  },
  {
    id: "CLT-1005",
    name: "Owen Fitzgerald",
    type: "Residential",
    status: "Active",
    primaryContactName: "Owen Fitzgerald",
    email: "owen.fitzgerald@example.com",
    phone: "(925) 555-0164",
    billingAddress: { street: "56 Ridgeline Ct", city: "Walnut Creek", state: "CA", zip: "94596" },
    originAddress: { street: "56 Ridgeline Ct", city: "Walnut Creek", state: "CA", zip: "94596" },
    destinationAddress: { street: "310 Bayshore Blvd", city: "Concord", state: "CA", zip: "94520" },
    accountOwner: "Omar Haddad",
    createdDate: "2026-07-28",
    lastActivityDate: "2026-08-21",
  },
  {
    id: "CLT-1006",
    name: "Harborline Dental Group",
    type: "Commercial",
    status: "Active",
    primaryContactName: "Dr. Renata Silva",
    email: "renata.silva@example.com",
    phone: "(510) 555-0129",
    billingAddress: { street: "220 Broadway", city: "Oakland", state: "CA", zip: "94607" },
    originAddress: { street: "220 Broadway", city: "Oakland", state: "CA", zip: "94607" },
    destinationAddress: { street: "48 Telegraph Ave", city: "Berkeley", state: "CA", zip: "94704" },
    accountOwner: "Fatima Rahman",
    createdDate: "2026-06-11",
    lastActivityDate: "2026-08-19",
  },
  {
    id: "CLT-1007",
    name: "Marcus Ainsley",
    type: "Residential",
    status: "Inactive",
    primaryContactName: "Marcus Ainsley",
    email: "marcus.ainsley@example.com",
    phone: "(408) 555-0157",
    billingAddress: { street: "1180 Foxworthy Ave", city: "San Jose", state: "CA", zip: "95118" },
    accountOwner: "Sofia Marchetti",
    createdDate: "2025-09-05",
    lastActivityDate: "2025-09-22",
    notes: "Move postponed indefinitely, follow up next quarter.",
  },
  {
    id: "CLT-1008",
    name: "Lena Brandt",
    type: "Residential",
    status: "In Storage",
    primaryContactName: "Lena Brandt",
    email: "lena.brandt@example.com",
    phone: "(650) 555-0136",
    billingAddress: { street: "39 Cedar Ln", city: "San Mateo", state: "CA", zip: "94402" },
    originAddress: { street: "39 Cedar Ln", city: "San Mateo", state: "CA", zip: "94402" },
    accountOwner: "Omar Haddad",
    createdDate: "2026-02-27",
    lastActivityDate: "2026-08-05",
  },
  {
    id: "CLT-1009",
    name: "Ferro Metalworks",
    type: "Commercial",
    status: "Active",
    primaryContactName: "Diego Ferro",
    email: "diego.ferro@example.com",
    phone: "(510) 555-0182",
    billingAddress: { street: "3300 Industrial Pkwy", city: "Hayward", state: "CA", zip: "94545" },
    originAddress: { street: "3300 Industrial Pkwy", city: "Hayward", state: "CA", zip: "94545" },
    destinationAddress: { street: "5000 Warehouse Row", city: "Fremont", state: "CA", zip: "94538" },
    accountOwner: "Sam Okafor",
    createdDate: "2026-04-16",
    lastActivityDate: "2026-08-17",
  },
  {
    id: "CLT-1010",
    name: "Yusuf Karimi",
    type: "Residential",
    status: "Lead",
    primaryContactName: "Yusuf Karimi",
    email: "yusuf.karimi@example.com",
    phone: "(408) 555-0148",
    billingAddress: { street: "812 Blossom Hill Rd", city: "San Jose", state: "CA", zip: "95123" },
    accountOwner: "Sofia Marchetti",
    createdDate: "2026-08-18",
    lastActivityDate: "2026-08-23",
  },
  {
    id: "CLT-1011",
    name: "Chen Family Trust",
    type: "Residential",
    status: "Past",
    primaryContactName: "Grace Chen",
    email: "grace.chen.trust@example.com",
    phone: "(650) 555-0121",
    billingAddress: { street: "1900 University Ave", city: "Palo Alto", state: "CA", zip: "94303" },
    originAddress: { street: "1900 University Ave", city: "Palo Alto", state: "CA", zip: "94303" },
    destinationAddress: { street: "700 Alma Real Dr", city: "Mountain View", state: "CA", zip: "94040" },
    accountOwner: "Fatima Rahman",
    createdDate: "2025-05-30",
    lastActivityDate: "2025-07-11",
  },
  {
    id: "CLT-1012",
    name: "Bright Horizon Preschool",
    type: "Commercial",
    status: "Active",
    primaryContactName: "Tasha Freeman",
    email: "tasha.freeman@example.com",
    phone: "(925) 555-0173",
    billingAddress: { street: "601 School House Rd", city: "Pleasanton", state: "CA", zip: "94588" },
    originAddress: { street: "601 School House Rd", city: "Pleasanton", state: "CA", zip: "94588" },
    destinationAddress: { street: "88 Learning Ln", city: "Dublin", state: "CA", zip: "94568" },
    accountOwner: "Omar Haddad",
    createdDate: "2026-07-01",
    lastActivityDate: "2026-08-16",
  },
  {
    id: "CLT-1013",
    name: "Isabel Moreno",
    type: "Residential",
    status: "Active",
    primaryContactName: "Isabel Moreno",
    email: "isabel.moreno@example.com",
    phone: "(408) 555-0165",
    billingAddress: { street: "45 Meridian Ave", city: "San Jose", state: "CA", zip: "95126" },
    originAddress: { street: "45 Meridian Ave", city: "San Jose", state: "CA", zip: "95126" },
    destinationAddress: { street: "220 Castro St", city: "Mountain View", state: "CA", zip: "94041" },
    accountOwner: "Sam Okafor",
    createdDate: "2026-08-02",
    lastActivityDate: "2026-08-24",
  },
  {
    id: "CLT-1014",
    name: "Redline Auto Detailing",
    type: "Commercial",
    status: "Inactive",
    primaryContactName: "Carlos Nunez",
    email: "carlos.nunez@example.com",
    phone: "(510) 555-0159",
    billingAddress: { street: "2100 Auto Mall Pkwy", city: "Fremont", state: "CA", zip: "94538" },
    accountOwner: "Sofia Marchetti",
    createdDate: "2025-12-08",
    lastActivityDate: "2026-01-15",
    notes: "Lost to a competitor's bid, revisit in a year.",
  },
  {
    id: "CLT-1015",
    name: "Harold Weiss",
    type: "Residential",
    status: "In Storage",
    primaryContactName: "Harold Weiss",
    email: "harold.weiss@example.com",
    phone: "(650) 555-0187",
    billingAddress: { street: "12 Sea Cliff Ter", city: "San Mateo", state: "CA", zip: "94404" },
    originAddress: { street: "12 Sea Cliff Ter", city: "San Mateo", state: "CA", zip: "94404" },
    accountOwner: "Fatima Rahman",
    createdDate: "2026-01-22",
    lastActivityDate: "2026-08-09",
  },
  {
    id: "CLT-1016",
    name: "Odessa Fields",
    type: "Residential",
    status: "Lead",
    primaryContactName: "Odessa Fields",
    email: "odessa.fields@example.com",
    phone: "(408) 555-0174",
    billingAddress: { street: "930 Coleman Ave", city: "Santa Clara", state: "CA", zip: "95050" },
    accountOwner: "Omar Haddad",
    createdDate: "2026-08-19",
    lastActivityDate: "2026-08-25",
  },
  {
    id: "CLT-1017",
    name: "Nguyen & Park Orthodontics",
    type: "Commercial",
    status: "Active",
    primaryContactName: "Dr. Kevin Park",
    email: "kevin.park@example.com",
    phone: "(408) 555-0198",
    billingAddress: { street: "2777 Stevens Creek Blvd", city: "San Jose", state: "CA", zip: "95128" },
    originAddress: { street: "2777 Stevens Creek Blvd", city: "San Jose", state: "CA", zip: "95128" },
    destinationAddress: { street: "10 Almaden Blvd", city: "San Jose", state: "CA", zip: "95113" },
    accountOwner: "Sam Okafor",
    createdDate: "2026-03-25",
    lastActivityDate: "2026-08-12",
  },
  {
    id: "CLT-1018",
    name: "Theodore Banks",
    type: "Residential",
    status: "Past",
    primaryContactName: "Theodore Banks",
    email: "theodore.banks@example.com",
    phone: "(925) 555-0142",
    billingAddress: { street: "76 Oak Grove Rd", city: "Concord", state: "CA", zip: "94518" },
    originAddress: { street: "76 Oak Grove Rd", city: "Concord", state: "CA", zip: "94518" },
    destinationAddress: { street: "410 Ygnacio Valley Rd", city: "Walnut Creek", state: "CA", zip: "94596" },
    accountOwner: "Sofia Marchetti",
    createdDate: "2025-08-04",
    lastActivityDate: "2025-09-01",
  },
  {
    id: "CLT-1019",
    name: "Amara Okonkwo",
    type: "Residential",
    status: "Active",
    primaryContactName: "Amara Okonkwo",
    email: "amara.okonkwo@example.com",
    phone: "(510) 555-0166",
    billingAddress: { street: "515 Grand Ave", city: "Oakland", state: "CA", zip: "94610" },
    originAddress: { street: "515 Grand Ave", city: "Oakland", state: "CA", zip: "94610" },
    destinationAddress: { street: "1400 Shattuck Ave", city: "Berkeley", state: "CA", zip: "94709" },
    accountOwner: "Fatima Rahman",
    createdDate: "2026-08-05",
    lastActivityDate: "2026-08-23",
  },
  {
    id: "CLT-1020",
    name: "Cascade Wealth Advisors",
    type: "Commercial",
    status: "Lead",
    primaryContactName: "Brian Holt",
    email: "brian.holt@example.com",
    phone: "(650) 555-0129",
    billingAddress: { street: "400 Concar Dr", city: "San Mateo", state: "CA", zip: "94402" },
    accountOwner: "Omar Haddad",
    createdDate: "2026-08-21",
    lastActivityDate: "2026-08-25",
    notes: "Wants a weekend move to avoid business downtime.",
  },
  {
    id: "CLT-1021",
    name: "Rosalind Pierce",
    type: "Residential",
    status: "Inactive",
    primaryContactName: "Rosalind Pierce",
    email: "rosalind.pierce@example.com",
    phone: "(408) 555-0119",
    billingAddress: { street: "660 Saratoga Ave", city: "San Jose", state: "CA", zip: "95129" },
    accountOwner: "Sam Okafor",
    createdDate: "2025-10-17",
    lastActivityDate: "2025-11-02",
  },
  {
    id: "CLT-1022",
    name: "Milestone Physical Therapy",
    type: "Commercial",
    status: "Active",
    primaryContactName: "Jordan Alvarez",
    email: "jordan.alvarez@example.com",
    phone: "(510) 555-0144",
    billingAddress: { street: "39500 Stevenson Pl", city: "Fremont", state: "CA", zip: "94539" },
    originAddress: { street: "39500 Stevenson Pl", city: "Fremont", state: "CA", zip: "94539" },
    destinationAddress: { street: "43000 Mission Blvd", city: "Fremont", state: "CA", zip: "94539" },
    accountOwner: "Sofia Marchetti",
    createdDate: "2026-05-20",
    lastActivityDate: "2026-08-13",
  },
  {
    id: "CLT-1023",
    name: "Felix Duarte",
    type: "Residential",
    status: "In Storage",
    primaryContactName: "Felix Duarte",
    email: "felix.duarte@example.com",
    phone: "(408) 555-0177",
    billingAddress: { street: "205 Vine Ave", city: "Sunnyvale", state: "CA", zip: "94086" },
    originAddress: { street: "205 Vine Ave", city: "Sunnyvale", state: "CA", zip: "94086" },
    accountOwner: "Omar Haddad",
    createdDate: "2026-03-09",
    lastActivityDate: "2026-08-07",
  },
  {
    id: "CLT-1024",
    name: "Greenline Landscaping",
    type: "Commercial",
    status: "Past",
    primaryContactName: "Walter Meyers",
    email: "walter.meyers@example.com",
    phone: "(925) 555-0188",
    billingAddress: { street: "1100 Contra Costa Blvd", city: "Concord", state: "CA", zip: "94520" },
    originAddress: { street: "1100 Contra Costa Blvd", city: "Concord", state: "CA", zip: "94520" },
    destinationAddress: { street: "2200 Monument Blvd", city: "Concord", state: "CA", zip: "94520" },
    accountOwner: "Fatima Rahman",
    createdDate: "2025-06-27",
    lastActivityDate: "2025-08-15",
  },
  {
    id: "CLT-1025",
    name: "Sasha Petrov",
    type: "Residential",
    status: "Active",
    primaryContactName: "Sasha Petrov",
    email: "sasha.petrov@example.com",
    phone: "(650) 555-0155",
    billingAddress: { street: "88 Alameda de las Pulgas", city: "Redwood City", state: "CA", zip: "94062" },
    originAddress: { street: "88 Alameda de las Pulgas", city: "Redwood City", state: "CA", zip: "94062" },
    destinationAddress: { street: "301 Ravenswood Ave", city: "Menlo Park", state: "CA", zip: "94025" },
    accountOwner: "Sam Okafor",
    createdDate: "2026-08-15",
    lastActivityDate: "2026-08-24",
  },
];

export const filters = {
  type: ["All", "Residential", "Commercial"],
  status: ["All", "Lead", "Active", "In Storage", "Past", "Inactive"],
  accountOwner: ["All", "Sam Okafor", "Fatima Rahman", "Omar Haddad", "Sofia Marchetti"],
};

export const statusMeta: Record<ClientStatus, { badgeClass: string; dotClass: string }> = {
  Lead: {
    badgeClass: "border-amber-500/20 bg-amber-500/10 text-amber-600 dark:text-amber-400",
    dotClass: "bg-amber-500",
  },
  Active: {
    badgeClass: "border-emerald-500/20 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
    dotClass: "bg-emerald-500",
  },
  "In Storage": {
    badgeClass: "border-sky-500/20 bg-sky-500/10 text-sky-600 dark:text-sky-400",
    dotClass: "bg-sky-500",
  },
  Past: {
    badgeClass: "border-border bg-muted/50 text-muted-foreground",
    dotClass: "bg-muted-foreground",
  },
  Inactive: {
    badgeClass: "border-orange-500/20 bg-orange-500/10 text-orange-600 dark:text-orange-400",
    dotClass: "bg-orange-500",
  },
};

export function formatAddress(address?: Address) {
  if (!address) return undefined;
  return `${address.street}, ${address.city}, ${address.state} ${address.zip}`;
}
